import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Header from "../_components/header/Header";
import ReduxProvider from "../../Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Header />
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
