import "./styles/globals.scss";

import type { Metadata } from "next";

import { Inter } from "next/font/google";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import Header from "../_components/header/Header";

import ReduxProvider from "../../Provider";
import { getServerSession } from "next-auth";
import SessionProvider from "../../SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <SessionProvider session={session}>
            <Header />
            <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
